config/routes.rb
DueloTempoReal::Application.routes.draw do
  resources :duelo_pessoas

  resources :duelos

  resources :pessoas
  
  match 'duelo_pessoas/:duelo_id/salva_redis_voto' => 'duelo_pessoas#salva_redis_voto', via: [:get]
  match '/consolida_votos/:duelo_id' => 'duelo_pessoas#consolida_votos', via: [:get]

end

app/models/duelo.rb
class Duelo < ActiveRecord::Base
  attr_accessible :data_fim, :data_inicio
  validates :data_inicio, :presence => true
end

app/models/duelo_pessoa.rb
class DueloPessoa < ActiveRecord::Base
  belongs_to :duelo
  belongs_to :pessoa
  attr_accessible :votos, :duelo_id, :pessoa_id
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  attr_accessible :descricao, :imagem, :nome
  validates :nome, :imagem, :presence => true
end

app/models/voto.rb
require 'redis'

class Voto < ActiveRecord::Base
  validates :duelo_pessoa_id, :qtd_voto, :data_consolidacao, :presence => true
  belongs_to :duelo_pessoa
  attr_accessible :data_consolidacao, :qtd_voto, :duelo_pessoa_id

  REDIS_HOST = 'localhost'
  REDIS_PORT = 6379

  @redis = Redis.new(host: REDIS_HOST, port: REDIS_PORT)

  def self.salva_no_redis(id_duelo, id_pessoa)
    @redis.hincrby("duelo-#{id_duelo}", "pessoa-#{id_pessoa}", 1)
  end
  
  def self.consolida_votos(duelo_id)
    votos_redis = @redis.hgetall("duelo-#{duelo_id}")
    votos_redis.each do |chave, valor|
      duelo_pessoa = chave.split('-')[1]
      qtd_voto = valor
      Voto.create(duelo_pessoa_id: duelo_pessoa, qtd_voto: qtd_voto, data_consolidacao: Time.now)
      participante_duelo = DueloPessoa.find_by_pessoa_id(duelo_pessoa)
      participante_duelo.update_attribute(:votos, qtd_voto)
    end
    puts "OLA!"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  self.allow_forgery_protection = false
end

app/controllers/duelo_pessoas_controller.rb
class DueloPessoasController < ApplicationController

  def salva_redis_voto
    duelo_pessoa = DueloPessoa.find(params[:duelo_id])
    duelo_id = duelo_pessoa.duelo_id
    pessoa_id = duelo_pessoa.pessoa.id
    @voto = Voto.salva_no_redis(duelo_id, pessoa_id)
  end
  
  def consolida_votos
    duelo_id = params[:duelo_id]
    Voto.consolida_votos(duelo_id)
  end

  # GET /duelo_pessoas
  # GET /duelo_pessoas.json
  def index
    @duelo_pessoas = DueloPessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @duelo_pessoas }
    end
  end

  # GET /duelo_pessoas/1
  # GET /duelo_pessoas/1.json
  def show
    @duelo_pessoa = DueloPessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @duelo_pessoa }
    end
  end

  # GET /duelo_pessoas/new
  # GET /duelo_pessoas/new.json
  def new
    @duelo_pessoa = DueloPessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @duelo_pessoa }
    end
  end

  # GET /duelo_pessoas/1/edit
  def edit
    @duelo_pessoa = DueloPessoa.find(params[:id])
  end

  # POST /duelo_pessoas
  # POST /duelo_pessoas.json
  def create
    @duelo_pessoa = DueloPessoa.new(params[:duelo_pessoa])

    respond_to do |format|
      if @duelo_pessoa.save
        format.html { redirect_to @duelo_pessoa, notice: 'Duelo pessoa was successfully created.' }
        format.json { render json: @duelo_pessoa, status: :created, location: @duelo_pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @duelo_pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /duelo_pessoas/1
  # PUT /duelo_pessoas/1.json
  def update
    @duelo_pessoa = DueloPessoa.find(params[:id])

    respond_to do |format|
      if @duelo_pessoa.update_attributes(params[:duelo_pessoa])
        format.html { redirect_to @duelo_pessoa, notice: 'Duelo pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @duelo_pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duelo_pessoas/1
  # DELETE /duelo_pessoas/1.json
  def destroy
    @duelo_pessoa = DueloPessoa.find(params[:id])
    @duelo_pessoa.destroy

    respond_to do |format|
      format.html { redirect_to duelo_pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/duelos_controller.rb
class DuelosController < ApplicationController

  # GET /duelos
  # GET /duelos.json
  def index
    @duelos = Duelo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @duelos }
    end
  end

  # GET /duelos/1
  # GET /duelos/1.json
  def show
    @duelo_pessoa = DueloPessoa.find(:all, :conditions => {:duelo_id => params[:id]})

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @duelo_pessoa }
    end
  end

  # GET /duelos/new
  # GET /duelos/new.json
  def new
    @duelo = Duelo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @duelo }
    end
  end

  # GET /duelos/1/edit
  def edit
    @duelo = Duelo.find(params[:id])
  end

  # POST /duelos
  # POST /duelos.json
  def create
    @duelo = Duelo.new(params[:duelo])

    respond_to do |format|
      if @duelo.save
        format.html { redirect_to @duelo, notice: 'Duelo was successfully created.' }
        format.json { render json: @duelo, status: :created, location: @duelo }
      else
        format.html { render action: "new" }
        format.json { render json: @duelo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /duelos/1
  # PUT /duelos/1.json
  def update
    @duelo = Duelo.find(params[:id])

    respond_to do |format|
      if @duelo.update_attributes(params[:duelo])
        format.html { redirect_to @duelo, notice: 'Duelo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @duelo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duelos/1
  # DELETE /duelos/1.json
  def destroy
    @duelo = Duelo.find(params[:id])
    @duelo.destroy

    respond_to do |format|
      format.html { redirect_to duelos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # protect_from_forgery :except => :index
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/duelo_pessoas_helper.rb
module DueloPessoasHelper
end

app/helpers/duelos_helper.rb
module DuelosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/duelo_pessoas/_form.html.erb
<%= form_for(@duelo_pessoa) do |f| %>
  <% if @duelo_pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duelo_pessoa.errors.count, "error") %> prohibited this duelo_pessoa from being saved:</h2>

      <ul>
      <% @duelo_pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :duelo %><br />
    <%= f.text_field :duelo %>
  </div>
  <div class="field">
    <%= f.label :pessoa %><br />
    <%= f.text_field :pessoa %>
  </div>
  <div class="field">
    <%= f.label :votos %><br />
    <%= f.number_field :votos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/duelo_pessoas/edit.html.erb
<h1>Editing duelo_pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @duelo_pessoa %> |
<%= link_to 'Back', duelo_pessoas_path %>

app/views/duelo_pessoas/index.html.erb
<h1>Listing duelo_pessoas</h1>

<table>
  <tr>
    <th>Duelo</th>
    <th>Pessoa</th>
    <th>Votos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @duelo_pessoas.each do |duelo_pessoa| %>
  <tr>
    <td><%= duelo_pessoa.duelo %></td>
    <td><%= duelo_pessoa.pessoa %></td>
    <td><%= duelo_pessoa.votos %></td>
    <td><%= link_to 'Show', duelo_pessoa %></td>
    <td><%= link_to 'Edit', edit_duelo_pessoa_path(duelo_pessoa) %></td>
    <td><%= link_to 'Destroy', duelo_pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Duelo pessoa', new_duelo_pessoa_path %>

app/views/duelo_pessoas/new.html.erb
<h1>New duelo_pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', duelo_pessoas_path %>

app/views/duelo_pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Duelo:</b>
  <%= @duelo_pessoa.duelo %>
</p>

<p>
  <b>Pessoa:</b>
  <%= @duelo_pessoa.pessoa %>
</p>

<p>
  <b>Votos:</b>
  <%= @duelo_pessoa.votos %>
</p>


<%= link_to 'Edit', edit_duelo_pessoa_path(@duelo_pessoa) %> |
<%= link_to 'Back', duelo_pessoas_path %>

app/views/duelos/_form.html.erb
<%= form_for(@duelo) do |f| %>
  <% if @duelo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duelo.errors.count, "error") %> prohibited this duelo from being saved:</h2>

      <ul>
      <% @duelo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_inicio %><br />
    <%= f.datetime_select :data_inicio %>
  </div>
  <div class="field">
    <%= f.label :data_fim %><br />
    <%= f.datetime_select :data_fim %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/duelos/edit.html.erb
<h1>Editing duelo</h1>

<%= render 'form' %>

<%= link_to 'Show', @duelo %> |
<%= link_to 'Back', duelos_path %>

app/views/duelos/index.html.erb
<h1>Listing duelos</h1>

<table>
  <tr>
    <th>Pessoa</th>
    <th>Data inicio</th>
    <th>Data fim</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @duelos.each do |duelo| %>
  <tr>
    <td><%= duelo.data_inicio %></td>
    <td><%= duelo.data_fim %></td>
    <td><%= link_to 'Show', duelo %></td>
    <td><%= link_to 'Edit', edit_duelo_path(duelo) %></td>
    <td><%= link_to 'Destroy', duelo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Duelo', new_duelo_path %>

app/views/duelos/new.html.erb
<h1>New duelo</h1>

<%= render 'form' %>

<%= link_to 'Back', duelos_path %>

app/views/duelos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="row">
        <div class="widget-duelo-tempo-real span5">
            <div class="container-widget">
                <h3 class="titulo-duelo">Quem está melhor agora</h3>

                <div class="container-barra-andamento">
                    <span class="porcentagem">35%</span>
                    <span class="porcentagem participante-1">65%</span>
                </div>

                <div class="container-participantes">
                    <% @duelo_pessoa.each_with_index do |duelo_pessoa, index|%>
                        <div class="participante participante-<%= index %>">
                            <img class="imagem-participante" src="<%= duelo_pessoa.pessoa.imagem %>" alt="">
                            <p class="nome-participante"><%= duelo_pessoa.pessoa.nome %></p>
                            <button class="btn btn-voto" data-duelo-id="<%= duelo_pessoa.duelo.id %>" data-duelo-pessoa-id="<%= duelo_pessoa.id %>" data-participante-id="<%= duelo_pessoa.pessoa.id %>">Bom golpe</button>
                        </div>
                    <% end %>
                </div>

                <div class="container-historico">
                    
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DueloTempoReal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br />
    <%= f.text_field :imagem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Imagem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.descricao %></td>
    <td><%= pessoa.imagem %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @pessoa.descricao %>
</p>

<p>
  <b>Imagem:</b>
  <%= @pessoa.imagem %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>